// flow-typed signature: 0d7178838a21150ea3657f2026877cba
// flow-typed version: <<STUB>>/react-waterfall_v4.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waterfall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waterfall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waterfall/dist/react-waterfall.dev' {
  declare module.exports: any;
}

declare module 'react-waterfall/dist/react-waterfall.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waterfall/dist/react-waterfall.dev.js' {
  declare module.exports: $Exports<'react-waterfall/dist/react-waterfall.dev'>;
}
declare module 'react-waterfall/dist/react-waterfall.min.js' {
  declare module.exports: $Exports<'react-waterfall/dist/react-waterfall.min'>;
}
declare module 'react-waterfall/index' {
  declare module.exports: $Exports<'react-waterfall'>;
}
declare module 'react-waterfall/index.js' {
  declare module.exports: $Exports<'react-waterfall'>;
}
